/*
MobileRobots Advanced Robotics Interface for Applications (ARIA)
Copyright (C) 2004, 2005 ActivMedia Robotics LLC
Copyright (C) 2006, 2007, 2008, 2009, 2010 MobileRobots Inc.
Copyright (C) 2011, 2012 Adept Technology

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

If you wish to redistribute ARIA under different terms, contact 
MobileRobots for information about a commercial version of ARIA at 
robots@mobilerobots.com or 
MobileRobots Inc, 10 Columbia Drive, Amherst, NH 03031; 800-639-9481
*/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArLMS2xxPacketReceiver {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArLMS2xxPacketReceiver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArLMS2xxPacketReceiver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      AriaJavaJNI.delete_ArLMS2xxPacketReceiver(swigCPtr);
    }
    swigCPtr = 0;
  }

  public ArLMS2xxPacketReceiver(short receivingAddress, boolean allocatePackets, boolean useBase0Address) {
    this(AriaJavaJNI.new_ArLMS2xxPacketReceiver__SWIG_0(receivingAddress, allocatePackets, useBase0Address), true);
  }

  public ArLMS2xxPacketReceiver(short receivingAddress, boolean allocatePackets) {
    this(AriaJavaJNI.new_ArLMS2xxPacketReceiver__SWIG_1(receivingAddress, allocatePackets), true);
  }

  public ArLMS2xxPacketReceiver(short receivingAddress) {
    this(AriaJavaJNI.new_ArLMS2xxPacketReceiver__SWIG_2(receivingAddress), true);
  }

  public ArLMS2xxPacketReceiver() {
    this(AriaJavaJNI.new_ArLMS2xxPacketReceiver__SWIG_3(), true);
  }

  public ArLMS2xxPacketReceiver(ArDeviceConnection deviceConnection, short receivingAddress, boolean allocatePackets, boolean useBase0Address) {
    this(AriaJavaJNI.new_ArLMS2xxPacketReceiver__SWIG_4(ArDeviceConnection.getCPtr(deviceConnection), deviceConnection, receivingAddress, allocatePackets, useBase0Address), true);
  }

  public ArLMS2xxPacketReceiver(ArDeviceConnection deviceConnection, short receivingAddress, boolean allocatePackets) {
    this(AriaJavaJNI.new_ArLMS2xxPacketReceiver__SWIG_5(ArDeviceConnection.getCPtr(deviceConnection), deviceConnection, receivingAddress, allocatePackets), true);
  }

  public ArLMS2xxPacketReceiver(ArDeviceConnection deviceConnection, short receivingAddress) {
    this(AriaJavaJNI.new_ArLMS2xxPacketReceiver__SWIG_6(ArDeviceConnection.getCPtr(deviceConnection), deviceConnection, receivingAddress), true);
  }

  public ArLMS2xxPacketReceiver(ArDeviceConnection deviceConnection) {
    this(AriaJavaJNI.new_ArLMS2xxPacketReceiver__SWIG_7(ArDeviceConnection.getCPtr(deviceConnection), deviceConnection), true);
  }

  public ArLMS2xxPacket receivePacket(long msWait) {
    long cPtr = AriaJavaJNI.ArLMS2xxPacketReceiver_receivePacket__SWIG_0(swigCPtr, this, msWait);
    return (cPtr == 0) ? null : new ArLMS2xxPacket(cPtr, false);
  }

  public ArLMS2xxPacket receivePacket() {
    long cPtr = AriaJavaJNI.ArLMS2xxPacketReceiver_receivePacket__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ArLMS2xxPacket(cPtr, false);
  }

  public void setDeviceConnection(ArDeviceConnection deviceConnection) {
    AriaJavaJNI.ArLMS2xxPacketReceiver_setDeviceConnection(swigCPtr, this, ArDeviceConnection.getCPtr(deviceConnection), deviceConnection);
  }

  public ArDeviceConnection getDeviceConnection() {
    long cPtr = AriaJavaJNI.ArLMS2xxPacketReceiver_getDeviceConnection(swigCPtr, this);
    return (cPtr == 0) ? null : new ArDeviceConnection(cPtr, false);
  }

  public boolean isAllocatingPackets() {
    return AriaJavaJNI.ArLMS2xxPacketReceiver_isAllocatingPackets(swigCPtr, this);
  }

}
