/*
MobileRobots Advanced Robotics Interface for Applications (ARIA)
Copyright (C) 2004, 2005 ActivMedia Robotics LLC
Copyright (C) 2006, 2007, 2008, 2009, 2010 MobileRobots Inc.
Copyright (C) 2011, 2012 Adept Technology

     This program is free software; you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation; either version 2 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program; if not, write to the Free Software
     Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

If you wish to redistribute ARIA under different terms, contact 
MobileRobots for information about a commercial version of ARIA at 
robots@mobilerobots.com or 
MobileRobots Inc, 10 Columbia Drive, Amherst, NH 03031; 800-639-9481
*/
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArRobotParams extends ArConfig {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArRobotParams(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArRobotParamsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArRobotParams obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      AriaJavaJNI.delete_ArRobotParams(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public ArRobotParams() {
    this(AriaJavaJNI.new_ArRobotParams(), true);
  }

  public String getClassName() {
    return AriaJavaJNI.ArRobotParams_getClassName(swigCPtr, this);
  }

  public String getSubClassName() {
    return AriaJavaJNI.ArRobotParams_getSubClassName(swigCPtr, this);
  }

  public double getRobotRadius() {
    return AriaJavaJNI.ArRobotParams_getRobotRadius(swigCPtr, this);
  }

  public double getRobotDiagonal() {
    return AriaJavaJNI.ArRobotParams_getRobotDiagonal(swigCPtr, this);
  }

  public double getRobotWidth() {
    return AriaJavaJNI.ArRobotParams_getRobotWidth(swigCPtr, this);
  }

  public double getRobotLength() {
    return AriaJavaJNI.ArRobotParams_getRobotLength(swigCPtr, this);
  }

  public double getRobotLengthFront() {
    return AriaJavaJNI.ArRobotParams_getRobotLengthFront(swigCPtr, this);
  }

  public double getRobotLengthRear() {
    return AriaJavaJNI.ArRobotParams_getRobotLengthRear(swigCPtr, this);
  }

  public boolean isHolonomic() {
    return AriaJavaJNI.ArRobotParams_isHolonomic(swigCPtr, this);
  }

  public boolean hasMoveCommand() {
    return AriaJavaJNI.ArRobotParams_hasMoveCommand(swigCPtr, this);
  }

  public int getAbsoluteMaxVelocity() {
    return AriaJavaJNI.ArRobotParams_getAbsoluteMaxVelocity(swigCPtr, this);
  }

  public int getAbsoluteMaxRotVelocity() {
    return AriaJavaJNI.ArRobotParams_getAbsoluteMaxRotVelocity(swigCPtr, this);
  }

  public int getAbsoluteMaxLatVelocity() {
    return AriaJavaJNI.ArRobotParams_getAbsoluteMaxLatVelocity(swigCPtr, this);
  }

  public boolean getRequestIOPackets() {
    return AriaJavaJNI.ArRobotParams_getRequestIOPackets(swigCPtr, this);
  }

  public boolean getRequestEncoderPackets() {
    return AriaJavaJNI.ArRobotParams_getRequestEncoderPackets(swigCPtr, this);
  }

  public int getSwitchToBaudRate() {
    return AriaJavaJNI.ArRobotParams_getSwitchToBaudRate(swigCPtr, this);
  }

  public double getAngleConvFactor() {
    return AriaJavaJNI.ArRobotParams_getAngleConvFactor(swigCPtr, this);
  }

  public double getDistConvFactor() {
    return AriaJavaJNI.ArRobotParams_getDistConvFactor(swigCPtr, this);
  }

  public double getVelConvFactor() {
    return AriaJavaJNI.ArRobotParams_getVelConvFactor(swigCPtr, this);
  }

  public double getRangeConvFactor() {
    return AriaJavaJNI.ArRobotParams_getRangeConvFactor(swigCPtr, this);
  }

  public double getDiffConvFactor() {
    return AriaJavaJNI.ArRobotParams_getDiffConvFactor(swigCPtr, this);
  }

  public double getVel2Divisor() {
    return AriaJavaJNI.ArRobotParams_getVel2Divisor(swigCPtr, this);
  }

  public double getGyroScaler() {
    return AriaJavaJNI.ArRobotParams_getGyroScaler(swigCPtr, this);
  }

  public boolean haveTableSensingIR() {
    return AriaJavaJNI.ArRobotParams_haveTableSensingIR(swigCPtr, this);
  }

  public boolean haveNewTableSensingIR() {
    return AriaJavaJNI.ArRobotParams_haveNewTableSensingIR(swigCPtr, this);
  }

  public boolean haveFrontBumpers() {
    return AriaJavaJNI.ArRobotParams_haveFrontBumpers(swigCPtr, this);
  }

  public int numFrontBumpers() {
    return AriaJavaJNI.ArRobotParams_numFrontBumpers(swigCPtr, this);
  }

  public boolean haveRearBumpers() {
    return AriaJavaJNI.ArRobotParams_haveRearBumpers(swigCPtr, this);
  }

  public int numRearBumpers() {
    return AriaJavaJNI.ArRobotParams_numRearBumpers(swigCPtr, this);
  }

  public int getNumIR() {
    return AriaJavaJNI.ArRobotParams_getNumIR(swigCPtr, this);
  }

  public boolean haveIR(int number) {
    return AriaJavaJNI.ArRobotParams_haveIR(swigCPtr, this, number);
  }

  public int getIRX(int number) {
    return AriaJavaJNI.ArRobotParams_getIRX(swigCPtr, this, number);
  }

  public int getIRY(int number) {
    return AriaJavaJNI.ArRobotParams_getIRY(swigCPtr, this, number);
  }

  public int getIRType(int number) {
    return AriaJavaJNI.ArRobotParams_getIRType(swigCPtr, this, number);
  }

  public int getIRCycles(int number) {
    return AriaJavaJNI.ArRobotParams_getIRCycles(swigCPtr, this, number);
  }

  public int getNumSonar() {
    return AriaJavaJNI.ArRobotParams_getNumSonar(swigCPtr, this);
  }

  public boolean haveSonar(int number) {
    return AriaJavaJNI.ArRobotParams_haveSonar(swigCPtr, this, number);
  }

  public int getSonarX(int number) {
    return AriaJavaJNI.ArRobotParams_getSonarX(swigCPtr, this, number);
  }

  public int getSonarY(int number) {
    return AriaJavaJNI.ArRobotParams_getSonarY(swigCPtr, this, number);
  }

  public int getSonarTh(int number) {
    return AriaJavaJNI.ArRobotParams_getSonarTh(swigCPtr, this, number);
  }

  public boolean getLaserPossessed() {
    return AriaJavaJNI.ArRobotParams_getLaserPossessed(swigCPtr, this);
  }

  public String getLaserType(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserType__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserType() {
    return AriaJavaJNI.ArRobotParams_getLaserType__SWIG_1(swigCPtr, this);
  }

  public String getLaserPortType(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserPortType__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserPortType() {
    return AriaJavaJNI.ArRobotParams_getLaserPortType__SWIG_1(swigCPtr, this);
  }

  public String getLaserPort(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserPort__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserPort() {
    return AriaJavaJNI.ArRobotParams_getLaserPort__SWIG_1(swigCPtr, this);
  }

  public boolean getConnectLaser(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getConnectLaser__SWIG_0(swigCPtr, this, laserNumber);
  }

  public boolean getConnectLaser() {
    return AriaJavaJNI.ArRobotParams_getConnectLaser__SWIG_1(swigCPtr, this);
  }

  public boolean getLaserFlipped(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserFlipped__SWIG_0(swigCPtr, this, laserNumber);
  }

  public boolean getLaserFlipped() {
    return AriaJavaJNI.ArRobotParams_getLaserFlipped__SWIG_1(swigCPtr, this);
  }

  public boolean getLaserPowerControlled(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserPowerControlled__SWIG_0(swigCPtr, this, laserNumber);
  }

  public boolean getLaserPowerControlled() {
    return AriaJavaJNI.ArRobotParams_getLaserPowerControlled__SWIG_1(swigCPtr, this);
  }

  public int getLaserMaxRange(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserMaxRange__SWIG_0(swigCPtr, this, laserNumber);
  }

  public int getLaserMaxRange() {
    return AriaJavaJNI.ArRobotParams_getLaserMaxRange__SWIG_1(swigCPtr, this);
  }

  public int getLaserCumulativeBufferSize(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserCumulativeBufferSize__SWIG_0(swigCPtr, this, laserNumber);
  }

  public int getLaserCumulativeBufferSize() {
    return AriaJavaJNI.ArRobotParams_getLaserCumulativeBufferSize__SWIG_1(swigCPtr, this);
  }

  public int getLaserX(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserX__SWIG_0(swigCPtr, this, laserNumber);
  }

  public int getLaserX() {
    return AriaJavaJNI.ArRobotParams_getLaserX__SWIG_1(swigCPtr, this);
  }

  public int getLaserY(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserY__SWIG_0(swigCPtr, this, laserNumber);
  }

  public int getLaserY() {
    return AriaJavaJNI.ArRobotParams_getLaserY__SWIG_1(swigCPtr, this);
  }

  public double getLaserTh(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserTh__SWIG_0(swigCPtr, this, laserNumber);
  }

  public double getLaserTh() {
    return AriaJavaJNI.ArRobotParams_getLaserTh__SWIG_1(swigCPtr, this);
  }

  public int getLaserZ(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserZ__SWIG_0(swigCPtr, this, laserNumber);
  }

  public int getLaserZ() {
    return AriaJavaJNI.ArRobotParams_getLaserZ__SWIG_1(swigCPtr, this);
  }

  public String getLaserIgnore(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserIgnore__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserIgnore() {
    return AriaJavaJNI.ArRobotParams_getLaserIgnore__SWIG_1(swigCPtr, this);
  }

  public String getLaserStartDegrees(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserStartDegrees__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserStartDegrees() {
    return AriaJavaJNI.ArRobotParams_getLaserStartDegrees__SWIG_1(swigCPtr, this);
  }

  public String getLaserEndDegrees(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserEndDegrees__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserEndDegrees() {
    return AriaJavaJNI.ArRobotParams_getLaserEndDegrees__SWIG_1(swigCPtr, this);
  }

  public String getLaserDegreesChoice(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserDegreesChoice__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserDegreesChoice() {
    return AriaJavaJNI.ArRobotParams_getLaserDegreesChoice__SWIG_1(swigCPtr, this);
  }

  public String getLaserIncrement(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserIncrement__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserIncrement() {
    return AriaJavaJNI.ArRobotParams_getLaserIncrement__SWIG_1(swigCPtr, this);
  }

  public String getLaserIncrementChoice(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserIncrementChoice__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserIncrementChoice() {
    return AriaJavaJNI.ArRobotParams_getLaserIncrementChoice__SWIG_1(swigCPtr, this);
  }

  public String getLaserUnitsChoice(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserUnitsChoice__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserUnitsChoice() {
    return AriaJavaJNI.ArRobotParams_getLaserUnitsChoice__SWIG_1(swigCPtr, this);
  }

  public String getLaserReflectorBitsChoice(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserReflectorBitsChoice__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserReflectorBitsChoice() {
    return AriaJavaJNI.ArRobotParams_getLaserReflectorBitsChoice__SWIG_1(swigCPtr, this);
  }

  public String getLaserStartingBaudChoice(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserStartingBaudChoice__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserStartingBaudChoice() {
    return AriaJavaJNI.ArRobotParams_getLaserStartingBaudChoice__SWIG_1(swigCPtr, this);
  }

  public String getLaserAutoBaudChoice(int laserNumber) {
    return AriaJavaJNI.ArRobotParams_getLaserAutoBaudChoice__SWIG_0(swigCPtr, this, laserNumber);
  }

  public String getLaserAutoBaudChoice() {
    return AriaJavaJNI.ArRobotParams_getLaserAutoBaudChoice__SWIG_1(swigCPtr, this);
  }

  public boolean hasSettableVelMaxes() {
    return AriaJavaJNI.ArRobotParams_hasSettableVelMaxes(swigCPtr, this);
  }

  public int getTransVelMax() {
    return AriaJavaJNI.ArRobotParams_getTransVelMax(swigCPtr, this);
  }

  public int getRotVelMax() {
    return AriaJavaJNI.ArRobotParams_getRotVelMax(swigCPtr, this);
  }

  public boolean hasSettableAccsDecs() {
    return AriaJavaJNI.ArRobotParams_hasSettableAccsDecs(swigCPtr, this);
  }

  public int getTransAccel() {
    return AriaJavaJNI.ArRobotParams_getTransAccel(swigCPtr, this);
  }

  public int getTransDecel() {
    return AriaJavaJNI.ArRobotParams_getTransDecel(swigCPtr, this);
  }

  public int getRotAccel() {
    return AriaJavaJNI.ArRobotParams_getRotAccel(swigCPtr, this);
  }

  public int getRotDecel() {
    return AriaJavaJNI.ArRobotParams_getRotDecel(swigCPtr, this);
  }

  public boolean hasLatVel() {
    return AriaJavaJNI.ArRobotParams_hasLatVel(swigCPtr, this);
  }

  public int getLatVelMax() {
    return AriaJavaJNI.ArRobotParams_getLatVelMax(swigCPtr, this);
  }

  public int getLatAccel() {
    return AriaJavaJNI.ArRobotParams_getLatAccel(swigCPtr, this);
  }

  public int getLatDecel() {
    return AriaJavaJNI.ArRobotParams_getLatDecel(swigCPtr, this);
  }

  public boolean save() {
    return AriaJavaJNI.ArRobotParams_save(swigCPtr, this);
  }

  public int getGPSX() {
    return AriaJavaJNI.ArRobotParams_getGPSX(swigCPtr, this);
  }

  public int getGPSY() {
    return AriaJavaJNI.ArRobotParams_getGPSY(swigCPtr, this);
  }

  public int getGPSBaud() {
    return AriaJavaJNI.ArRobotParams_getGPSBaud(swigCPtr, this);
  }

  public String getGPSPort() {
    return AriaJavaJNI.ArRobotParams_getGPSPort(swigCPtr, this);
  }

  public String getGPSType() {
    return AriaJavaJNI.ArRobotParams_getGPSType(swigCPtr, this);
  }

  public String getCompassType() {
    return AriaJavaJNI.ArRobotParams_getCompassType(swigCPtr, this);
  }

  public String getCompassPort() {
    return AriaJavaJNI.ArRobotParams_getCompassPort(swigCPtr, this);
  }

}
